HEMS_ACCEPT = ['aggregator_distribution', 'aggregator_dr_event']
BEMS_ACCEPT = ['appliances']

HOST = '0.0.0.0'
PORT = 5000

API_URI = 'https://nodes.thetangle.org:443'
# 'http://node.deviceproof.org:14265'
api_name = 'dlt'
MySeed = b"LUEMBUSKXRNZQO9ZFLHNVCRMJD9QISVRALLJZPMKXQCMJLSYTAGZR9ILUL9NODGKHLGWHZSKJQTMP9AOF"
TARGETADDRESS = b"VOBLCCGXZOHUWUWTYJBZUFQBTDEOC9UZTUCORAKPAXPZLXRVWDZDKOIQHWIYXSCMKFMWYYCZBUHRWQSHX"
